MvcBookStore/Controllers/BookStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcBookStore.Models;
using PagedList;
using PagedList.Mvc;
namespace MvcBookStore.Controllers
{
    public class BookStoreController : Controller
    {
        //
        // GET: /BookStore/
        dbQLbansachDataContext data = new dbQLbansachDataContext();
        private List<SACH> Laysachmoi(int count)
        {
            return data.SACHes.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        public ActionResult Index(int? page)
        {

            int pageSize = 5;
            int pageNum = (page ?? 1);
            var sachmoi = Laysachmoi(15);          
            return View(sachmoi.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Chude()
        {
            var chude = from cd in data.CHUDEs select cd;
            return PartialView(chude);
        }
        public ActionResult Nhaxuatban()
        {
            var nhaxuatban = from nxb in data.NHAXUATBANs select nxb;
            return PartialView(nhaxuatban);
        }
        
        public ActionResult SPTheochude(int id )
        {
            var sach = from s in data.SACHes where s.MaCD == id select s;
            return View(sach);
        }
        public ActionResult SPTheoNXB(int id)
        {
            var sach = from s in data.SACHes where s.MaNXB == id select s;
            return View(sach);
        }
        public ActionResult Details(int id)
        {
            var sach = from s in data.SACHes
                       where s.Masach == id
                       select s;
            return View(sach.Single());
        }
        

	}
}

MvcBookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MvcBookStore/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <link href="~/Content/style.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.4.1.min.js"></script>
    <script src="~/Scripts/jquery-func.js"></script>
    <script src="~/Scripts/jquery.jcarousel.pack.js"></script>
    <script src="~/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>
</head>
<body>

    <!-- Shell -->
    <div class="shell">
        

        @*<h3 style="color : coral ; text-align : center;background:black"> Nguyễn Hải Duy Đức - 15DH110065- ca 1</h3>*@



        <div id="header">
            <h1 id="logo"><a href="#">shoparound</a></h1>
            <!-- Cart -->
            
            <!-- End Cart -->
            <!-- Navigation -->
            <div id="navigation">
                <ul>
                    @*<li><a href="#" class="active">Home</a></li>
                    <li><a href="#">Support</a></li>
                    <li><a href="#">My Account</a></li>
                    <li><a href="#">The Store</a></li>
                    <li><a href="#">Contact</a></li>*@
                    <li> @Html.ActionLink("TRANG CHỦ", "Index", "Admin") </li>
                    <li> @Html.ActionLink("QUẢN LÝ CHỦ ĐỀ", "Sanpham", "Admin") </li>
                    <li> @Html.ActionLink("NHÀ XUẤT BẢN", "Nhaxuatban", "Admin") </li>
                    <li> @Html.ActionLink("QUẢN LÝ SÁCH", "Sach", "Admin")</li>
                    <li><a href="#">CONTACT</a></li>


                </ul>
            </div>
            <div>
                @RenderBody()
            </div>
            <!-- End Navigation -->
        </div>

        

        



        @*<div id="footer">
            <p class="left"> <a href="#">Home</a> <span>|</span> <a href="#">Support</a> <span>|</span> <a href="#">My Account</a> <span>|</span> <a href="#">The Store</a> <span>|</span> <a href="#">Contact</a> </p>
            <p class="right"> &copy; 2010 Shop Around. Design by <a href="http://chocotemplates.com">Chocotemplates.com</a> </p>
        </div>*@
        <!-- End Footer -->
    </div>
    <!-- End Shell -->
    @*<div align=center>This template  downloaded form <a href='http://all-free-download.com/free-website-templates/'>free website templates</a></div>*@
</body>
</html>

MvcBookStore/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <link href="~/Content/style.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.4.1.min.js"></script>
    <script src="~/Scripts/jquery-func.js"></script>
    <script src="~/Scripts/jquery.jcarousel.pack.js"></script>
</head>
<body>
    
    <!-- Shell -->
    <div class="shell">
        <!-- Header -->
        <div id="header">
            <h1 id="logo"><a href="#">shoparound</a></h1>
            <!-- Cart -->
            <div id="cart">
                <a href="~/GioHang/GioHang" class="cart-link">Giỏ Hàng Của Bạn</a>
                
                <div class="cl">&nbsp;</div>
                @*<span>Articles: <strong>4</strong></span> &nbsp;&nbsp; <span>Cost: <strong>$250.99</strong></span>*@
            </div>
            <!-- End Cart -->
            <!-- Navigation -->
            <div id="navigation">
                <ul>
                    <li><a href="~/BookStore/Index" class="active">Trang Chủ</a></li>
                    <li><a href="~/Admin/Login">Đăng Nhập </a></li>
                    @*<li><a href="#">My Account</a></li>
                    <li><a href="#">The Store</a></li>
                    <li><a href="#">Contact</a></li>*@
                </ul>
                @using (Html.BeginForm("Index", "BookStore", FormMethod.Get, new { @class = "navbar-form navbar-right", role = "search", id = "search-form" }))
                {
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Tìm kiếm sách" name="SearchTerm" value="@ViewBag.SearchTerm" id="search-box">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default hidden-xs"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                }
            </div>
            <!-- End Navigation -->
        </div>
        <!-- End Header -->
        <!-- Main -->
        <div id="main">
            <div class="cl">&nbsp;</div>
            <div id="sidebar">
                <!-- Search -->
                <!-- End Search -->
                <!-- Categories -->
                <div class="box categories">
                    <div class="container">
                        @*<h2>Categories <span></span></h2>*@
                        <div class="row">
                            @*<div class="col-md-3">*@
                                @Html.Action("ChuDe", "BookStore")
                                @Html.Action("NhaXuatBan","Bookstore")
                            @*</div>*@
                        </div>
                    </div>
                    @*<h2>Categories <span></span></h2>*@
                         
                    @*<div class="box-content">
                        <ul>
                            <li><a href="#">Category 1</a></li>
                            <li><a href="#">Category 2</a></li>
                            <li><a href="#">Category 3</a></li>
                            <li><a href="#">Category 4</a></li>
                            <li><a href="#">Category 5</a></li>
                            <li><a href="#">Category 6</a></li>
                            <li><a href="#">Category 7</a></li>
                            <li><a href="#">Category 8</a></li>
                            <li><a href="#">Category 9</a></li>
                            <li><a href="#">Category 10</a></li>
                            <li><a href="#">Category 11</a></li>
                            <li><a href="#">Category 12</a></li>
                            <li class="last"><a href="#">Category 13</a></li>
                        </ul>
                    </div>*@
                </div>
                <!-- End Categories -->
            </div>
            <div>
                @RenderBody()
            </div>

            <!-- End Content -->
            <!-- End Search -->
            <!-- Categories -->
            <!-- End Categories -->
        </div>
        <!-- End Sidebar -->
        <div class="cl">&nbsp;</div>
        <!-- End Main -->
        <!-- Side Full -->
        <div class="side-full">
            <!-- More Products -->
            <div class="more-products">
                <div class="more-products-holder">
                    <ul>

                        <li><a href="#"><img src="~/Hinhsanpham/KT0001.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0002.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0003.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0004.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0005.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0006.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0007.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0008.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0009.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0001.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0002.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0003.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0004.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0005.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0006.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0007.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0008.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0009.jpg" alt="" /></a></li>
                        <li><a href="#"><img src="~/Hinhsanpham/KT0005.jpg" alt="" /></a></li>
                        <li class="last"><a href="#"><img src="~/images/small7.jpg" alt="" /></a></li>
                    </ul>
                </div>
                <div class="more-nav"> <a href="#" class="prev">previous</a> <a href="#" class="next">next</a> </div>
            </div>
            <!-- End More Products -->
            <!-- Text Cols -->
            <div class="cols">
                <div class="cl">&nbsp;</div>
                <div class="col">
                    <h3 class="ico ico1">Liên Hệ</h3>
                    <p>Cửa hàng sách DD</p>
                    <p>111 Sư Vạn Hạnh Phường 10 Quận 10, TP.HCM </p>
                </div>
                <div class="col">
                    <h3 class="ico ico2">Điện Thoại</h3>
                    <p>097474745.</p>
                    
                </div>
                @*<div class="col">
                    <h3 class="ico ico3">Donec imperdiet</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec imperdiet, metus ac cursus auctor, arcu felis ornare dui.</p>
                    <p class="more"><a href="#" class="bul">Lorem ipsum</a></p>
                </div>
                <div class="col col-last">
                    <h3 class="ico ico4">Donec imperdiet</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec imperdiet, metus ac cursus auctor, arcu felis ornare dui.</p>
                    <p class="more"><a href="#" class="<b>content</b>ul">Lorem ipsum</a></p>
                </div>*@
                <div class="cl">&nbsp;</div>
            </div>
            <!-- End Text Cols -->
        </div>
        <!-- End Side Full -->
        <!-- Footer -->
        <div id="footer">
            <p class="left"> <a href="~/BookStore/Index">Trang chủ</a> <span>|</span> <a href="#">Support</a> <span>|</span> <a href="~/Admin/Login">Đăng Nhập</a> <span>|</span> <a href="#">Cửa Hàng</a> <span>|</span> <a href="#">Contact</a> </p>
            <p class="right"> &copy; 2010 Shop Around. Design by <a href="http://chocotemplates.com">Chocotemplates.com</a> </p>
        </div>
        <!-- End Footer -->
    </div>
    <!-- End Shell -->
    <div align=center>This template  downloaded form <a href='http://all-free-download.com/free-website-templates/'>free website templates</a></div>
</body>
</html>